# Generated by Django 5.1.3 on 2024-11-23 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Вариант D')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('user_answer', models.CharField(max_length=1, verbose_name='Ответ пользователя')),
                ('correct', models.BooleanField(verbose_name='Правильно ли')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
            ],
        ),
    ]
